# TODO: 'schedules' will need to be updated to coincide with the meeting frequency

name: Schedule TSC meetings
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: wesleytodd/meeting-maker@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-05-14T17:00:00.0Z/P4W
        createWithin: P1D
        issueTitle: "TSC Meeting <%= date.toFormat('yyyy-MM-dd') %>"
        agendaLabel: meeting-agenda
